export const PaymentTypes: { [key: string]: string } = {
  WebATM_TAISHIN: "台新銀行WebATM",
  WebATM_ESUN: "玉山銀行WebATM",
  WebATM_BOT: "台灣銀行WebATM",
  WebATM_FUBON: "台北富邦WebATM",
  WebATM_CHINATRUST: "中國信託WebATM",
  WebATM_FIRST: "第一銀行WebATM",
  WebATM_CATHAY: "國泰世華WebATM",
  WebATM_MEGA: "兆豐銀行WebATM",
  WebATM_LAND: "土地銀行WebATM",
  WebATM_SINOPAC: "永豐銀行WebATM",
  ATM_TAISHIN: "台新銀行ATM",
  ATM_ESUN: "玉山銀行ATM",
  ATM_BOT: "台灣銀行ATM",
  ATM_FUBON: "台北富邦ATM",
  ATM_CHINATRUST: "中國信託ATM",
  ATM_FIRST: "第一銀行ATM",
  ATM_LAND: "土地銀行ATM",
  ATM_CATHAY: "國泰世華銀行ATM",
  ATM_PANHSIN: "板信銀行ATM",
  ATM_KGI: "凱基銀行ATM",
  CVS_CVS: "超商代碼繳款",
  CVS_OK: "OK超商代碼繳款",
  CVS_FAMILY: "全家超商代碼繳款",
  CVS_HILIFE: "萊爾富超商代碼繳款",
  CVS_IBON: "7-11 ibon代碼繳款",
  BARCODE_BARCODE: "超商條碼繳款",
  Credit_CreditCard: "信用卡",
  Flexible_Installment: "圓夢彈性分期",
  TWQR_OPAY: "歐付寶TWQR 行動支付",
  BNPL_URICH: "裕富數位無卡分期",
};
