name: 構建與部署測試機

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    name: 構建與部署
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v4

      - name: 設置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 設置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登入 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 構建並推送 Docker 映像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eventa-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/eventa-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/eventa-backend:buildcache,ignore-error=true
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/eventa-backend:buildcache,mode=max

      - name: 觸發 Render 部署
        if: success()
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"